
# Defaults to "serve index.php" and "serve public/index.php". Can be used to
# serve a custom PHP front controller (e.g. "serve backend/index.php") or to
# run a long-running PHP script as a worker process (e.g. "php worker.php").
#
# entrypoint: serve index.php

runtime: php82 # Replace with php74 to use PHP 7.4

# Serve your app through a front controller at index.php or public/index.php.
- url: .*
  script: auto
